[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pneumoai"
version = "0.1.0"
description = "PneumoAI production-style pneumonia inference service"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "Thiyaga" }
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]