name: Release Docker Image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/thiyaga1586/pneumoai

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS artifacts
        run: git lfs pull

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ github.sha }} \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:${{ github.ref_name }}
          docker push $IMAGE_NAME:latest